### ISSUE TITLE
Fix Balances contract commands

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-pruntime#13]
Currently `transfer(dest, amount)` resets the balance of `dest`. This is apparently not "transferring".

In order to create a transferable contract, we need:

- Fix the semantic of `transfer(dest, amount)`:
    1. Check `balance[origin] >= amount`
    2. `balance[origin] -= amount`
    3. `balance[dest] += amount`
- Initialize the contract with some balance. Let's issue some tokens to the built in account Alice ("d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d")

**Comment by Lawliet-Chan** [comment]
As you said, the `transfer execution` is a transferring behavior, not a transferring result.  
I think there's  something wrong with that.
At the first of pruntime starts running, there is no accounts in pruntime or  all the accounts are zero.  You should give a result value of transferring to pruntime, not giving a transferring behavior to let the pruntime to calculate the result value.
